# Generated by Django 6.0 on 2026-01-03 22:46

import json

import boto3
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def init_s3_bucket(apps, schema_editor):
    session = boto3.Session(
        aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
        aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
        region_name=settings.AWS_REGION,
    )
    bucket_name = settings.AWS_STORAGE_BUCKET_NAME
    s3 = session.resource(
        "s3",
        endpoint_url=settings.AWS_S3_ENDPOINT_URL,
    )
    if not s3.Bucket(bucket_name) in s3.buckets.all():
        s3.create_bucket(Bucket=bucket_name)
    s3_client = session.client(
        "s3",
        endpoint_url=settings.AWS_S3_ENDPOINT_URL,
    )

    s3_client.put_public_access_block(
        Bucket=bucket_name,
        PublicAccessBlockConfiguration={
            "BlockPublicAcls": False,
            "IgnorePublicAcls": False,
            "BlockPublicPolicy": False,
            "RestrictPublicBuckets": False,
        },
    )

    policy = {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "PublicReadForPath",
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": f"arn:aws:s3:::{bucket_name}/*",
            }
        ],
    }

    s3_client.put_bucket_policy(Bucket=bucket_name, Policy=json.dumps(policy))

    print("S3 bucket configured with public read access.")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("photo_url", models.URLField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
            ],
        ),
        migrations.RunPython(code=init_s3_bucket),
    ]
