# Generated by Django 6.0 on 2026-01-03 22:46

import json
from botocore.config import Config
import boto3
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from botocore.exceptions import ClientError

def init_s3_bucket(apps, schema_editor):
    session = boto3.Session(
        aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
        aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
        region_name=settings.AWS_REGION,
    )
    bucket_name = settings.AWS_STORAGE_BUCKET_NAME
    s3 = session.resource(
        "s3",
    )
    s3_client = session.client(
        "s3",
        region_name=settings.AWS_REGION,
    )

    try:
        s3_client.head_bucket(Bucket=bucket_name)
    except ClientError as e:
        error_code = e.response["Error"]["Code"]

        if error_code in ("404", "NoSuchBucket"):
            create_kwargs = {"Bucket": bucket_name}

            if settings.AWS_REGION != "us-east-1":
                create_kwargs["CreateBucketConfiguration"] = {
                    "LocationConstraint": settings.AWS_REGION
                }

            s3_client.create_bucket(**create_kwargs)
        else:
            raise


    s3_client.put_public_access_block(
        Bucket=bucket_name,
        PublicAccessBlockConfiguration={
            "BlockPublicAcls": False,
            "IgnorePublicAcls": False,
            "BlockPublicPolicy": False,
            "RestrictPublicBuckets": False,
        },
    )

    policy = {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "PublicReadForPath",
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": f"arn:aws:s3:::{bucket_name}/*",
            }
        ],
    }

    s3_client.put_bucket_policy(Bucket=bucket_name, Policy=json.dumps(policy))

    print("S3 bucket configured with public read access.")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("photo_url", models.URLField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
            ],
        ),
        #migrations.RunPython(code=init_s3_bucket),
    ]
