# Generated by Django 6.0 on 2026-01-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module", "0003_module_photo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="photo_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
