# Generated by Django 6.0 on 2025-12-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="validation_code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
