# Generated by Django 6.0 on 2025-12-29 22:18

from django.db import migrations, models

def delete_validation_codes(apps, schema_editor):
    User = apps.get_model('user', 'User')
    for user in User.objects.all():
        if user.validation_code == "":
            user.validation_code = None
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_validation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='validation_code',
            field=models.CharField(max_length=6, blank=True, null=True),
        ),
        migrations.RunPython(delete_validation_codes),
        migrations.AlterField(
            model_name='user',
            name='validation_code',
            field=models.IntegerField(max_length=6, blank=True, null=True),
        ),
    ]
