# Generated by Django 6.0 on 2025-12-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_validation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="validation_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
