# Generated by Django 6.0 on 2026-01-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_validation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="validation_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
