# Generated by Django 6.0 on 2026-01-03 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("questionbank", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("time_limit_in_minutes", models.PositiveSmallIntegerField()),
                ("randomize_question_order", models.BooleanField(default=False)),
                (
                    "show_correct_answers_on_completion",
                    models.BooleanField(default=False),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
                (
                    "question_banks",
                    models.ManyToManyField(to="questionbank.questionbank"),
                ),
            ],
        ),
    ]
