# Generated by Django 6.0 on 2026-01-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0003_remove_question_question_bank"),
        ("questionbank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="questions",
            field=models.ManyToManyField(
                blank=True, related_name="question_banks", to="question.question"
            ),
        ),
    ]
