# Generated by Django 6.0 on 2026-01-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionresponse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionresponse",
            name="instructor_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionresponse",
            name="points",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
