# Generated by Django 6.0 on 2026-01-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionresponse", "0002_questionresponse_instructor_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionresponse",
            name="selected_options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of selected option indices (1-based) for multiple choice",
            ),
        ),
    ]
