# Generated by Django 6.0 on 2026-01-26 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
        ("questionbank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.TextField(blank=True, help_text="Comma-separated tags"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="questionbank.questionbank",
            ),
        ),
    ]
