# Generated by Django 6.0 on 2026-01-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0002_question_tags_alter_question_question_bank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="question_bank",
        ),
    ]
