# Generated by Django 6.0 on 2026-01-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0003_remove_question_question_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiplechoiceoption",
            name="correct_options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of correct option indices (1-based) for multiple choice",
            ),
        ),
        migrations.AddField(
            model_name="multiplechoiceoption",
            name="is_multiple_choice",
            field=models.BooleanField(default=False),
        ),
    ]
