# Generated by Django 6.0 on 2026-01-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0004_multiplechoiceoption_correct_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplechoiceoption",
            name="correct_options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of correct option indices (1-based) for multiple choice",
                null=True,
            ),
        ),
    ]
